services:
  - type: web
    name: pixel-love-backend
    env: node
    buildCommand: npm run build
    startCommand: node dist/main.js
    envVars:
      - key: NODE_OPTIONS
        value: --max-old-space-size=180
      - key: NODE_ENV
        value: production

